### ISSUE TITLE
Improve script generation. 

### ISSUE THREAD

**Issue by hlasimpk** [rigdenlab/SIMBAD#16]
Generation of the scripts to run SIMBAD on one core produces a bottle neck when running the full MoRDa search. Running the script generation in parallel should significantly improve the performance.

Need to think about how this will work on SGE/LSF clusters too.

**Comment by fsimkovic** [comment]
This issue is linked to fsimkovic/pyjob#3.

**Comment by fsimkovic** [comment]
@hlasimpk Is this step fast enough now by generating a single script instead of 2?

**Comment by hlasimpk** [comment]
I think this has been improved sufficiently for now.
