### ISSUE TITLE
SIMBAD unable to import iotbx.pdb.mining

### ISSUE THREAD

**Issue by fsimkovic** [rigdenlab/SIMBAD#38]
Python import of `iotbx.pdb.mining` fails in `simbad.util.pdb_util`. The module was removed in CCP4 v7.0.48.

SIMBAD might run on machines that had CCP4 v7.0.47 installed and at least one successful import of `iotbx.pdb.mining` either through SIMBAD or any other package. This is due to the pre-created `mining.pyc` file.

**Comment by hlasimpk** [comment]
Fixed this issue by removing dependence on `iotbx.pdb.mining`
