### ISSUE TITLE
Incorrect PyJOB keyword argument

### ISSUE THREAD

**Issue by fsimkovic** [rigdenlab/SIMBAD#64]
Some  `pyjob.Job().submit()` calls include the `submit_queue` keyword, which results in the user-specified queue to be ignored. The actual keyword is `queue` and needs to be changed in SIMBAD accordingly.

**Comment by fsimkovic** [comment]
There is still another occurrence of this.

https://github.com/rigdenlab/SIMBAD/blob/bebe507b03f2bdc4685d11e36913fc87fbc1ca25/simbad/command_line/simbad_database.py#L314

**Comment by fsimkovic** [comment]
Maybe we should rename all the `-submit_<something>` flags to just the `<something>` part?! Although that might cause problems with JsCoFE now and users ... a mask?

**Comment by hlasimpk** [comment]
I've fixed the simbad_database errors. I've left the `-submit_<something>` flags as they are for now. I might consider changing it in the future.
