### ISSUE TITLE
amore_search return_z_score_results doe not return anything

### ISSUE THREAD

**Issue by fsimkovic** [rigdenlab/SIMBAD#8]
The `AmoreRotationSearch().return_z_score_results` does not return anything. Is this a deliberate decision @hlasimpk? We might want to rename this function in this case?

**Comment by hlasimpk** [comment]
I'll have a look, just adding some changes to the AmoreRotationSearch atm

**Comment by hlasimpk** [comment]
Ah, the naming on this one seems to be left over from how the code was before we re-factored it. This function used to return a named tuple, now it creates the _AmoreRotationScore object and sets this to _search_results. The results can now be retrieved using  rotation_search.search_results. I think this function just need renaming, however it also might be possible to get remove it and put the code else where

**Comment by hlasimpk** [comment]
Removed the function and the code has been added to the run_amore function
